// Generated by https://quicktype.io

export interface OpenaiErrorResponse {
    error: Error;
}

export interface Error {
    message: string;
    type:    string;
    param:   null;
    code:    null;
}
